---
############################################################
# SSH ACCESS HANDLERS
############################################################

- name: restart ssh
  service:
    name: ssh
    state: restarted
